/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import funcion.ContenidoCSV;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import funcion.GenerarDatos;
import funcion.GraficaSimulacion;
import funcion.GraficaSimulacionTn;
/**
 *
 * @author yael
 */
public class grafica extends javax.swing.JFrame {

    /**
     * Creates new form grafica
     */
    public grafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableCSV = new javax.swing.JTable();
        datoslbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        añosSlider = new javax.swing.JSlider();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Ingresar Datos(Exel)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackButton.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        JTableCSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTableCSV);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 570, 190));

        datoslbl.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(datoslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 330, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 130, 40));

        btnGenerar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 130, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 130, 40));

        añosSlider.setMajorTickSpacing(10);
        añosSlider.setPaintLabels(true);
        añosSlider.setPaintTicks(true);
        getContentPane().add(añosSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 280, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Graficar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 980, 160, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 710, 340));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setText("Graficar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 160, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1060, 700, 320));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, -30, -1, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents
ContenidoCSV contenidoCSV=new ContenidoCSV();
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
        Principal2 ventana = new Principal2();
        ventana.setVisible(true);

    }//GEN-LAST:event_jLabel5MouseClicked
private void cargarCsv() {
     ContenidoCSV contenidoCSV = new ContenidoCSV();
        
        // Cargar los datos desde el archivo CSV
        contenidoCSV.cargarDesdeArchivo();

        // Obtener los datos del archivo CSV
        String[] encabezados = contenidoCSV.obtenerEncabezados();
        List<String[]> filas = contenidoCSV.obtenerFilas();

        // Crear el modelo de la tabla con los encabezados
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(encabezados);

        // Agregar las filas al modelo
        for (String[] fila : filas) {
            model.addRow(fila);
        }

        // Asignar el modelo de la tabla al JTable
        JTableCSV.setModel(model);
}

private void calcularValores() {
    DefaultTableModel model = (DefaultTableModel) JTableCSV.getModel();
    int rowCount = model.getRowCount();
    if (rowCount == 0) {
        datoslbl.setText("La tabla está vacía. Carga un archivo CSV primero.");
        return;
    }

    // Asegurarse de que las columnas adicionales para resultados existan
    if (model.getColumnCount() < 6) {
        model.addColumn("Daño Ambiental");
        model.addColumn("Tasa de Natalidad Calculada");
        model.addColumn("Esperanza de Vida Calculada");
    }

    try {
        for (int i = 0; i < rowCount; i++) {
            double tasaNatalidadNormal = Double.parseDouble((String) model.getValueAt(i, 0));
            double esperanzaVidaNormal = Double.parseDouble((String) model.getValueAt(i, 1));
            double relacionDesechos = Double.parseDouble((String) model.getValueAt(i, 2));
            double ocupacionInadecuada = Double.parseDouble((String) model.getValueAt(i, 3));

            // Cálculo de daño ambiental
            double danioAmbiental = relacionDesechos + ocupacionInadecuada;

            // Cálculo de tasa de natalidad
            double tasaNatalidad = tasaNatalidadNormal - (danioAmbiental * 8.35e-5);

            // Cálculo de esperanza de vida
            double esperanzaVida = esperanzaVidaNormal * (1 - danioAmbiental * 0.07);

            // Agregar los resultados calculados directamente en las nuevas columnas
            model.setValueAt(String.format("%.4f", danioAmbiental), i, 4); // Columna "Daño Ambiental"
            model.setValueAt(String.format("%.4f", tasaNatalidad), i, 5); // Columna "Tasa de Natalidad Calculada"
            model.setValueAt(String.format("%.2f", esperanzaVida), i, 6); // Columna "Esperanza de Vida Calculada"
        }

        datoslbl.setText("Valores calculados y añadidos a la tabla.");
    } catch (Exception ex) {
        datoslbl.setText("Error en el cálculo: " + ex.getMessage());
    }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      cargarCsv();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        int cantidadDeFilas = añosSlider.getValue();  // 'añosSlider' es el slider con la cantidad de filas a generar

        // Llamar al método que genera los nuevos datos
        GenerarDatos.generarMasDatos(JTableCSV, cantidadDeFilas);      // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        calcularValores();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      GraficaSimulacion.graficarDesdeTabla(JTableCSV, jPanel1);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableCSV;
    private javax.swing.JSlider añosSlider;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel datoslbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
